# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, Qt
from PyQt5.QtWidgets import QMainWindow, QWidget, QApplication, QDialog
from PyQt5.QtGui import QPalette, QBrush, QPixmap, QImage
import tkinter as tk
from tkinter import filedialog
# from src.LPLocator.LPLocator import LPLocator
import Main


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("车牌号码识别")
        Form.resize(1050, 543)  # 793 543
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.Button_select = QtWidgets.QPushButton(Form)
        self.Button_select.setEnabled(True)
        self.Button_select.setObjectName("Button_select")
        self.Button_select.setFixedSize(100, 30)
        self.gridLayout.addWidget(self.Button_select, 2, 1, 1, 1)
        self.label_phote = QtWidgets.QLabel(Form)
        self.label_phote.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_phote.sizePolicy().hasHeightForWidth())
        self.label_phote.setSizePolicy(sizePolicy)
        self.label_phote.setMinimumSize(QtCore.QSize(400, 400))
        self.label_phote.setObjectName("label_phote")
        self.gridLayout.addWidget(self.label_phote, 0, 0, 1, 5)
        self.Button_exit = QtWidgets.QPushButton(Form)
        self.Button_exit.setObjectName("Button_exit")
        self.gridLayout.addWidget(self.Button_exit, 2, 3, 1, 1)
        self.Button_exit.setFixedSize(100, 30)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_located = QtWidgets.QLabel(Form)
        self.label_located.setObjectName("label_located")
        self.verticalLayout.addWidget(self.label_located)
        self.label_projection = QtWidgets.QLabel(Form)
        self.label_projection.setObjectName("label_projection")
        self.verticalLayout.addWidget(self.label_projection)
        self.label_division = QtWidgets.QLabel(Form)
        self.label_division.setObjectName("label_division")
        self.verticalLayout.addWidget(self.label_division)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_showresult = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.label_showresult.setFont(font)
        self.label_showresult.setObjectName("label_showresult")
        self.horizontalLayout.addWidget(self.label_showresult)
        self.lineEdit_result = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_result.setFont(font)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.horizontalLayout.addWidget(self.lineEdit_result)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "车牌号码识别"))
        self.Button_select.setText(_translate("Form", "选择识别图片"))
        self.label_phote.setText(_translate("Form", "选择的图片"))
        self.Button_exit.setText(_translate("Form", "退出"))
        self.label_located.setText(_translate("Form", "车牌定位图"))
        self.label_projection.setText(_translate("Form", "垂直投影图"))
        self.label_division.setText(_translate("Form", "车牌分割图"))
        self.label_showresult.setText(_translate("Form", "识别结果："))

        # self.retranslateUi(Form)
        # # self.Button_select.clicked['bool'].connect(self.label_projection.setDisabled)
        # QtCore.QMetaObject.connectSlotsByName(Form)

        self.Button_exit.clicked['bool'].connect(self.quit)
        self.Button_select.clicked['bool'].connect(self.select_picture)

    def quit(self):
        print("1")
        sys.exit()

    def select_picture(self):
        root = tk.Tk()
        root.withdraw()
        # Folderpath = filedialog.askdirectory()  # 获得选择好的文件夹
        Filepath = filedialog.askopenfilename()  # 获得选择好的文件
        print('Filepath:', Filepath)
        img = QImage(Filepath)  # 创建图片实例
        ratio = 1.5
        print(img.width())
        newWidth = int(610)
        newHeight = int(510)
        size = QSize(newWidth, newHeight)
        pixImg = QPixmap.fromImage(img.scaled(size, Qt.IgnoreAspectRatio))
        # 修改图片实例大小并从QImage实例中生成QPixmap实例以备放入QLabel控件中
        self.label_phote.resize(newWidth, newHeight)
        self.label_phote.setPixmap(pixImg)
        # print('Folderpath:', Folderpath)

        img_lp_highlighted, shadow_image, sliced_photos, result = Main.Main(Filepath)
        img_located = img_lp_highlighted
        shrink = cv2.cvtColor(img_located, cv2.COLOR_BGR2RGB)
        img_located = QtGui.QImage(shrink.data,
                                   shrink.shape[1],
                                   shrink.shape[0],
                                   shrink.shape[1] * 3,
                                   QtGui.QImage.Format_BGR888)

        newWidth_located = int(430)
        newHeight_located = int(300)
        size_located = QSize(newWidth_located, newHeight_located)
        self.label_phote.resize(newWidth, newHeight)
        self.label_located.setPixmap(QtGui.QPixmap.fromImage(img_located.scaled(size_located, Qt.IgnoreAspectRatio)))

        shrink = cv2.cvtColor(sliced_photos, cv2.COLOR_BGR2RGB)
        sliced_photos = QtGui.QImage(shrink.data,
                                     shrink.shape[1],
                                     shrink.shape[0],
                                     shrink.shape[1] * 3,
                                     QtGui.QImage.Format_BGR888)
        self.label_division.setPixmap(QtGui.QPixmap.fromImage(sliced_photos))

        shrink = cv2.cvtColor(shadow_image, cv2.COLOR_BGR2RGB)
        shadow_image = QtGui.QImage(shrink.data,
                                    shrink.shape[1],
                                    shrink.shape[0],
                                    shrink.shape[1] * 3,
                                    QtGui.QImage.Format_BGR888)
        self.label_projection.setPixmap(QtGui.QPixmap.fromImage(shadow_image))

        self.lineEdit_result.setText(result)
        print('Sliced photos:', sliced_photos)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = QWidget()
    ui = Ui_Form()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
